version: '3'
services:
  mongo:
    image: mongo:latest
    volumes:
      - './data:/data/db'
    networks:
      - backend
    restart: always

  redis:
    image: redis:latest
    networks:
      - backend
    restart: always

  secret-hitler:
    image: danwelcome/secret-hitler:latest
    ports:
      - '8080:8080'
    networks:
      - backend
    restart: always
    depends_on:
      - mongo
      - redis

networks:
  backend:
    driver: bridge
